#!/usr/bin/env python
"""
Shell Doctest module.

:Copyright: (c) 2009, the Shell Doctest Team All rights reserved.
:license: BSD, see LICENSE for more details.
"""

import StringIO
import fnmatch
import imp
import os.path

import shelldoctest

def _get_file_lists(target_paths):
    exists = list()
    no_exists = list()
    for path in target_paths:
        if not os.path.exists(path):
            no_exists.append(path)
        elif os.path.isfile(path):
            exists.append(path)
        else:
            for i in os.walk(path):
                if not i:
                    continue
                parent, dirs, files = i
                for f in files:
                    exists.append(os.path.sep.join([parent, f]))
    return exists, no_exists

def _get_mod_files(file_lists):
    results = list()
    for f in file_lists:
        if not fnmatch.fnmatch(f, "*.py"):
            continue
        if f.startswith("./"):
            f = f[2:]
        mod_name = os.path.splitext(f)[0].replace(os.path.sep, ".")
        results.append((mod_name, f))
    return results

def _pre(argv):
    if not argv:
        argv = ["."]
    file_lists, labels = _get_file_lists(argv)
    if not file_lists:
        file_lists, _labels = _get_file_lists(["."])
    mod_files = _get_mod_files(file_lists)
    return file_lists, mod_files, labels

def test(self, *argv):
    file_lists, mod_files, labels = _pre(argv)
    for mod_name, f in mod_files:
        try:
            mod = imp.load_source(mod_name, f)
        except ImportError, e:
            self.status_message("%(mod_name)s:ImportError, %(e)s" % vars(), verbose_level=2)
            continue
        else:
            self.status_message("Module:%(f)s" % vars(), verbose_level=2)
            shelldoctest.testmod(mod, verbose=self.verbose_level>2,
                                    verbose_level=self.verbose_level, filters=labels)

def labels(self, *argv):
    _file_lists, mod_files, _labels = _pre(argv)
    for mod_name, f in mod_files:
        _stderr = sys.stderr
        sys.stderr = StringIO.StringIO()
        try:
            mod = imp.load_source(mod_name, f)
        except ImportError, e:
            self.status_message("%(mod_name)s:ImportError, %(e)s" % vars(), verbose_level=2)
            continue
        else:
            self.status_message("Module:%(f)s" % vars(), verbose_level=2)
            __labels(mod, verbose=self.verbose_level>2,
                                    verbose_level=self.verbose_level, filters=None)
        finally:
            sys.stderr = _stderr

from shelldoctest import *
def __labels(m=None, name=None, globs=None, verbose=None,
            report=True, optionflags=doctest.ELLIPSIS, extraglobs=None,
            raise_on_error=False, exclude_empty=False,
            verbose_level=None, filters=None,
            ):
    if globs == None:
        globs = dict()
    globs.update({"system_command": system_command})
    global master
    if m is None:
        m = sys.modules.get('__main__')
    if not inspect.ismodule(m):
        raise TypeError("testmod: module required; %r" % (m,))
    if name is None:
        name = m.__name__
    finder = doctest.DocTestFinder(parser=ShellDocTestParser(), exclude_empty=exclude_empty)
    if raise_on_error:
        runner = doctest.DebugRunner(verbose=verbose, optionflags=optionflags)
    else:
        runner = ShellDocTestRunner(verbose=verbose, verbose_level=verbose_level, optionflags=optionflags)
    tests = finder.find(m, name, globs=globs, extraglobs=extraglobs)
    if filters:
        _tests = list()
        z = dict([(k,v) for v,k in enumerate(filters)])
        for test in tests:
            test.examples = sorted(filter(lambda x: x.label in filters, test.examples),
                                cmp=lambda x,y: cmp(z[x.label], z[y.label]))
            _tests.append(test)
        tests = _tests
    [[sys.stdout.write("[%s] %s:%s:\n" % (ex.label, test.filename, ex.lineno))
        for ex in test.examples if ex.label] for test in tests]

if __name__ == "__main__":
    from shelldoctest import base_app
    base_app.start_app()

